import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import worker from '../src/index.js';
const sql=new DatabaseSync(':memory:');
const db={prepare(query){return {args:[],bind(...args){this.args=args.map(x=>x instanceof ArrayBuffer?new Uint8Array(x):x);return this;},async first(){return sql.prepare(query).get(...this.args)||null;},async all(){return {results:sql.prepare(query).all(...this.args)};},async run(){return sql.prepare(query).run(...this.args);}};},async batch(statements){return Promise.all(statements.map(x=>x.run()));}};
const env={DB:db,ASSETS:{fetch:async()=>new Response('asset')}};
async function call(path,method='GET',data=null,cookie='',headers={}){return worker.fetch(new Request('https://aurapops.online'+path,{method,headers:{Origin:'https://aurapops.online',Cookie:cookie,'Content-Type':'application/json',...headers},body:data?JSON.stringify(data):undefined}),env);}
const register=async(name,email)=>{const r=await call('/api/aurapops/account/register','POST',{name,email,password:'a-strong-password-123'});assert.equal(r.status,201);return r.headers.get('set-cookie').split(';')[0];};
test('customer registration, ownership, legacy claim and payment activation remain isolated',async()=>{
 const a=await register('Alice','alice@example.com'),b=await register('Bob','bob@example.com');
 const anon=await call('/api/aurapops/account/pops');assert.equal(anon.status,401);
 const popBody={title:'Alice café',slug:'alice-cafe',links:[{type:'website',label:'Visit',url:'https://example.com'}]};
 const create=await call('/api/aurapops/pops','POST',popBody,a);assert.equal(create.status,201);const {pop,token}=await create.json();
 assert.equal((await (await call('/api/aurapops/account/pops','GET',null,a)).json()).items.length,1);
 assert.equal((await (await call('/api/aurapops/account/pops','GET',null,b)).json()).items.length,0);
 assert.equal((await call('/api/aurapops/pops/'+pop.id,'GET',null,b)).status,401);
 assert.equal((await call('/api/aurapops/pops/'+pop.id,'PATCH',{title:'Stolen'},b)).status,401);
 assert.equal(token,null);
 assert.equal((await call('/api/aurapops/account/claim','POST',{id:pop.id,token:'b'.repeat(64)},b)).status,403);
 assert.equal((await call('/api/aurapops/pops/'+pop.id,'PATCH',{title:'Updated',paymentStatus:'paid',status:'approved'},a)).status,200);
 assert.equal((await call('/api/aurapops/public/'+pop.slug)).status,404);
 const adminRaw='a'.repeat(64);const digest=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(adminRaw))).toString('hex');sql.prepare("INSERT INTO aurapops_admin_sessions VALUES (?,datetime('now','+1 day'),datetime('now'))").run(digest);const admin='__Host-aurapops_admin='+adminRaw;
 assert.equal((await call('/api/aurapops/admin/pops/'+pop.id,'PATCH',{status:'approved'},admin)).status,409);
 assert.equal((await call('/api/aurapops/admin/pops/'+pop.id,'PATCH',{status:'approved',paymentStatus:'paid'},admin)).status,200);
 assert.equal((await call('/api/aurapops/public/'+pop.slug)).status,200);
 const legacy=await (await call('/api/aurapops/pops','POST',{title:'Old draft',slug:'old-draft',links:[]})).json();
 assert.equal((await call('/api/aurapops/account/claim','POST',{id:legacy.pop.id,token:'f'.repeat(64)},a)).status,403);
 assert.equal((await call('/api/aurapops/account/claim','POST',{id:legacy.pop.id,token:legacy.token},a)).status,200);
 assert.equal((await call('/api/aurapops/pops/'+legacy.pop.id,'GET',null,'',{'X-AuraPop-Token':legacy.token})).status,401);
 assert.equal((await call('/api/aurapops/account/claim','POST',{id:legacy.pop.id,token:legacy.token},b)).status,409);
 assert.equal((await (await call('/api/aurapops/account/pops','GET',null,a)).json()).items.length,2);
 const login=await call('/api/aurapops/account/login','POST',{email:'alice@example.com',password:'wrong'});assert.equal(login.status,401);
 const correct=await call('/api/aurapops/account/login','POST',{email:'alice@example.com',password:'a-strong-password-123'});assert.equal(correct.status,200);assert.match(correct.headers.get('set-cookie'),/HttpOnly/);
 assert.equal((await call('/api/aurapops/account/password','POST',{currentPassword:'wrong',password:'new-password-123'},a)).status,401);
 assert.equal((await call('/api/aurapops/account/password','POST',{currentPassword:'a-strong-password-123',password:'new-password-123'},a)).status,200);
 assert.equal((await (await call('/api/aurapops/account/session','GET',null,a)).json()).user,null);
 const cross=await worker.fetch(new Request('https://aurapops.online/api/aurapops/account/login',{method:'POST',headers:{Origin:'https://evil.example'},body:'{}'}),env);assert.equal(cross.status,403);
 assert.equal((await call('/api/aurapops/account/google')).status,503);
 assert.equal((await call('/api/aurapops/account/google/callback?state=forged&code=fake')).status,302);
 const fresh=await call('/api/aurapops/account/login','POST',{email:'alice@example.com',password:'new-password-123'});assert.equal(fresh.status,200);const freshCookie=fresh.headers.get('set-cookie').split(';')[0];assert.equal((await call('/api/aurapops/account/logout','POST',{},freshCookie)).status,200);assert.equal((await (await call('/api/aurapops/account/session','GET',null,freshCookie)).json()).user,null);
});
